import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const imgLink =
  "https://image.tmdb.org/t/p/original/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg";

export const metadata = {
  title: "CineVerse - Gives you something to watch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main
          className={
            "container my-9 mx-auto h-main-h rounded-lg bg-cover bg-center bg-no-repeat"
          }
          style={{ backgroundImage: `url(${imgLink})` }}
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
